version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0.27'
    restart: 'unless-stopped'
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db_example
    volumes:
      - mysqldb:/var/lib/mysql
  demo:
    container_name: demo
    image: 'spring-boot-demo'
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=root
    depends_on:
      - mysql
volumes:
  mysqldb:

# mvn clean package -P prod -Dmaven.test.skip && docker build --no-cache  . -t spring-boot-demo